export const prefixApiPath = '/api'

export const apiPath = {
    init: 'init',
    member: '/member',
    enroll: '/member',
    logout: '/logout',
    login: '/login',
    line: '/line',
    lineCallback: '/line/callback',
    fb: '/fb',
    fbCallback: '/fb/callback',
    google: '/google',
    googleCallback: '/google/callback',
    password: '/password',
    forgotPassword: '/forgotPassword',
    memberInfo: '/memberInfo',
    getBusker: '/busker',
    enrollBusker: '/busker',
    performance: '/performance',
    performances: '/performances',
    performancesTime: '/performancesTime',
    performancesDonate: '/performancesDonate',
    onlineAmount: '/onlineAmount',
    commentAmount: '/commentAmount',
    weekCommentAmount: '/weekCommentAmount',
    futurePerformancesData: '/futurePerformancesData',
    confirmLineDonateOrder: '/confirmLineDonateOrder',
}
